# Generated by Django 6.1.1 on 2026-10-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='trabajador_asignado',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
